### ISSUE TITLE
Zuul Eureka and https problem

### ISSUE THREAD

**Issue by Jacuo** [spring-cloud/spring-cloud-netflix#1099]
i have problem with https services in my Gateway application ( which uses zuul )
I have exception 

```
caused by: java.lang.IllegalStateException: Could not create URI object: Expected scheme-specific part at index 6: https:
       at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:430) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
       at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$OverrideRestClient.reconstructURIWithServer(RibbonClientConfiguration.java:184) ~[spring-cloud-netflix-core-1
       at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:106) ~[ribbon-loadbalancer-2.1.5.jar:2.1.5]
       at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303) ~[ribbon-loadbalancer-2.1.5.jar:2.1.5]
       at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287) ~[ribbon-loadbalancer-2.1.5.jar:2.1.5]
       at rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:223) ~[rxjava-1.1.5.jar:1.1.5]
       at rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:220) ~[rxjava-1.1.5.jar:1.1.5]
       at rx.Observable.unsafeSubscribe(Observable.java:8460) ~[rxjava-1.1.5.jar:1.1.5]
       ... 150 common frames omitted
aused by: java.net.URISyntaxException: Expected scheme-specific part at index 6: https:
       at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_92]
       at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_92]
       at java.net.URI$Parser.parse(URI.java:3057) ~[na:1.8.0_92]
       at java.net.URI.<init>(URI.java:673) ~[na:1.8.0_92]

```

My Gateway config

```
server:
  ssl:
    key-store: classpath:my.jks
    key-store-password: secret
    key-password: secret 
spring:
  application:
    name: mille-gateway
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: mille-config-server
eureka:
  client:
    healthcheck:
      enabled: true
ribbon:
  IsSecure: true
zuul:
  ignoredServices: '*'
  routes:
     test:
      path: /test/**
      serviceId: mille-test2

test:
  ribbon:      
    ReadTimeout: 5000
    MaxAutoRetries: 2
    IsSecure: true
```

My Registry ( Eureka ) server
server:
  port: 8761

eureka:

```
 instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false     
```

My client configuration

```
spring:
  application:
    name: mille-test2
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: mille-config-server
eureka:
  client:
    healthcheck:
      enabled: true  
server:
  port: 50000
  ssl:
    key-store: classpath:my.jks
    key-store-password: secret
    key-password: secret 

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}    
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrl: https://${eureka.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
    metadataMap:
       hostname: ${eureka.instance.hostname}
       securePort: ${server.port}  
```

What could be a problem ?

**Comment by Jacuo** [comment]
Nobody knows ?

**Comment by kakawait** [comment]
Is normal that you are using `${eureka.hostname}` and not `${eureka.instance.hostname}`

**Comment by spencergibb** [comment]
@Jacuo do you have an example app that reproduces the problem?

**Comment by Jacuo** [comment]
Sorry, I was busy with other things, but I can provide example app

**Comment by bryan-helm** [comment]
This is also on [Stack Overflow:](http://stackoverflow.com/questions/37833756/spring-cloud-zuul-https/40433005#40433005)
I added a comment there giving the debug scenario for Brixton.SR6. Brixton.SR5 works, and the main difference is SR6 adding the 'true' parameter to the UriComponentBuilder.build call in RibbonUtils.updateToHttpsIfNeeded().

**Comment by spencergibb** [comment]
@bryan-helm can you supply a project that recreates the problem?

**Comment by bryan-helm** [comment]
Are the instructions on SO for reproduction not clear enough? If you use a standard Zuul server and have  a discoverable service for which the incoming url path match is exact, and ribbon.IsSecure=true, then you should see the problem, as I understand it. The key is that the uri is "" and https: is required. Are you asking me to provide an edge server and discoverable service for it to call? I guess I could do that, but the information I got out of the debugger and documented in the SO comment seems to make it more clear than that would. If you are saying this does not occur in a standard Brixton.SR6 setup, then I will look into creating a reproduction sequence that does not involve my real edge server and services.

**Comment by spencergibb** [comment]
@bryan-helm This issue has no mention of feign in this issue, your SO answer only mentions feign, not zuul. Wondering if they are the same issue.

**Comment by bryan-helm** [comment]
I am not positive it is the same issue since what I am describing is specific to Brixton.SR6, and this appears to predate that.  Feign is only involved because Ribbon under Zuul uses FeignLoadBalancer. Zuul is involved because the problem occurs making secure discoverable service calls. In my scenario, the exception occurs before we get to the call to super.reconstructURIWithServer() in FeignLoadBalancer.reconstructURIWithServer(), which appears to be what is in the stack trace above (AbstractLoadBalancerAwareClient is the parent class of FeignLoadBalancer). In SR6, there is a call to RibbonUtils.updateToHttpsIfNeeded() before the call to super.reconstructURIWithServer() that throws the exception (spring-cloud-netflix-core-1.1.6). It could be a similar issue though, calling new Uri() without all required uri components set. Would you like me to start a new issue? I stayed with this one because the exception was identical.

**Comment by spencergibb** [comment]
Ribbon under Zuul does not use FeignLoadBalancer, only `@FeignClient`s do. If you can provide a sample, create a new issue.

**Comment by bryan-helm** [comment]
OK, I will see what I can do, but I guarantee that Zuul uses FeignLoadBalancer in my setup, and not through any explicit coding on my part. It could be because we use Consul instead of Eureka.

**Comment by spencergibb** [comment]
If your zuul uses FeignLoadBalancer, something is very broken. I don't see how it can use `FeignLoadBalancer`

**Comment by bryan-helm** [comment]
We reverted to SR5 because it works, and it may be a bit before I can deploy SR6 again and find out where FeignLoadBalancer is coming from in the debugger like I did yesterday. I think that might be better than trying to provide an edge server and service to you. It is a bit difficult stepping through this stuff as it all happens asynchronously when RibbonRoutingFilter.forward() calls command.execute(). I will try to get to this later today.  Thanks for your attention.

**Comment by bryan-helm** [comment]
I was able to get an environment going with Brixton.SR6 today and reproduce this. I am not seeing FeignLoadBalancer in the stack trace (confused by that, but oh well), but the same problematic code is also in RibbonClientConfiguration.OverrideRestClient.reconstructURIWithServer(). It calls RibbonUtils.updateToHttpsIfNeeded() with the URI set to "", and the exception is thrown before that returns. I previously had the feign starter as a dependency, but removed it (no actual compile dependency), so that might have made a difference. At any rate, if this is fixed in RibbonUtils it will fix both OverrideRestClient and FeignLoadBalancer.  If fixed in reconstructURIWithServer(), you might need a fix in two places. Since the RibbonUtils updateToHttpsIfNeeded method has the Server instance, setting the host and port in the uri builder might be the simplest fix.

**Comment by ryanjbaxter** [comment]
@bryan-helm I am not following why the URI is "", can you elaborate?

**Comment by bryan-helm** [comment]
If the incoming url is /foo/bar and the zuul mapping is also /foo/bar, then the uri is "", as it is the remaining part of the path after the match. The zuul mapping looks like:
zuul.routes.service.path=/foo/bar
'service' is the name of a registered discoverable service. Note the path does not end with /**.

**Comment by ryanjbaxter** [comment]
u said above u had an environment to reproduce this, would it be possible to provide that to us?

**Comment by bryan-helm** [comment]
Unfortunately it is a larger project and is both proprietary and behind a firewall (still in development, not exposed publicly). We are using Consul for the config and discovery server, but using Zuul as the edge server.  I can try to answer questions or check out any theories in the debugger here. I can reproduce the problem easily, I just cannot work around it.  It seems pretty clear to me that the uri needs the server and port before calling new URI(toString()), or needs the server and port added before 'forcing' https.

**Comment by bryan-helm** [comment]
Here is a test case showing the RibbonUtils problem. The ServerInspector and Server are not accessed when ribbon.IsSecure is true.

```java
import static org.springframework.cloud.netflix.ribbon.RibbonUtils.updateToHttpsIfNeeded;

import java.net.URI;

import org.junit.Test;
import org.mockito.Mockito;
import org.springframework.cloud.netflix.ribbon.ServerIntrospector;

import com.netflix.client.config.CommonClientConfigKey;
import com.netflix.client.config.IClientConfig;
import com.netflix.loadbalancer.Server;

public class RibbonUtilsUriBug1099 {

    @Test
    public void testUpdateToHttpsIfNeededEmptyUri() throws Exception {
        IClientConfig config = Mockito.mock(IClientConfig.class);
        Mockito.when(config.get(CommonClientConfigKey.IsSecure)).thenReturn(Boolean.TRUE);
        updateToHttpsIfNeeded(new URI(""),config,(ServerIntrospector)null,(Server)null);
    }
}
```

**Comment by spencergibb** [comment]
The missing case for me was how to get an empty `URI`: having a path like @bryan-helm described `zuul.routes.service.path=/foo/bar`

**Comment by spencergibb** [comment]
Actually it doesn't help. I'm still unable to reproduce an empty URI.

**Comment by spencergibb** [comment]
This fixes it, but I want to know how to get an empty uri and fix that.

```
	public static URI updateToHttpsIfNeeded(URI uri, IClientConfig config, ServerIntrospector serverIntrospector,
			Server server) {
		String scheme = uri.getScheme();
		if (!"https".equals(scheme) && isSecure(config, serverIntrospector, server)) {
			UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromUri(uri).scheme("https");
			if (uri.getRawQuery() != null) {
				// When building the URI, UriComponentsBuilder verify the allowed characters and does not 
				// support the '+' so we replace it for its equivalent '%20'.
				// See issue https://jira.spring.io/browse/SPR-10172
				uriComponentsBuilder.replaceQuery(uri.getRawQuery().replace("+", "%20"));
			}
			if (!StringUtils.hasLength(uri.getRawPath())) {
				// will cause parse exception
				uriComponentsBuilder.host(server.getHost());
				uriComponentsBuilder.port(server.getPort());
			}
			return uriComponentsBuilder.build(true).toUri();
		}
		return uri;
	}
```

Passing test case:
```
	@Test
	public void testUpdateToHttpsIfNeededEmptyUri() throws Exception {
		IClientConfig config = mock(IClientConfig.class);
		when(config.get(CommonClientConfigKey.IsSecure)).thenReturn(Boolean.TRUE);
		URI uri = updateToHttpsIfNeeded(new URI(""), config, new DefaultServerIntrospector(), new Server("localhost", 443));
		assertThat("Empty uri now has host:port", uri, equalTo(new URI("https://localhost:443")));
	}
```

**Comment by bryan-helm** [comment]
I have never seen the uri be anything but "" when using service discovery. We are building our own service id to call `Route route = routeLocator.getMatchingRoute(**service**);` (i.e. not using service id from zuul route match for incoming url) and the `route.getPath()` is always "". That gets set as requestURI:  `ctx.put("requestURI", route.getPath());`.  What do you see as the uri?

BTW, thanks for the fix, anyway. Whenever it propagates through the Spring Cloud release train process, we will (hopefully) be able to go past Brixton.SR5 again.

**Comment by spencergibb** [comment]
@bryan-helm The fix isn't committed because I *never* see an empty uri. You are obviously doing some custom code that seems to be part of the cause. Why would you have an empty `path`?

**Comment by bryan-helm** [comment]
The discovery client does not get any path info when discovering registered services, only host and port. We struggled to try to get path info in the target url, but never succeeded, finally making the discoverable services support being called with no path (we were constrained to not add path components to the incoming url for backwards compatibility with a system we are replacing).

There is a path on the route found via the mapping we have for the incoming url, it matches the incoming url. For our case, that incoming url mapping service id is combined with other information to determine the actual service id to use in routing (i.e. there is not a one to one relationship between incoming url and service to be called). We do not use the PreDecorationFilter, but we do use logic similar to what is there to find a matching route for the target service, which was added to the Zuul route configuration via service discovery, and has no path.  I now suspect you are saying that Zuul only supports calling services by id that exactly match a route entry, which is not the case in Brixton.SR5 and some earlier versions, as this is what we have been doing for a while now.

```
zuul.routes.service.path=/foo/bar
```
Incoming url: /foo/bar
Assume there is a service registered with the name  "service-vendor".
Assume there is not any service registered named "service".
```
String serviceId = "service" + "-vendor";
Route route = routeLocator.getMatchingRoute(serviceId);
String location = route.getLocation();
if (location != null) {
    RequestContext ctx = RequestContext.getCurrentContext();
    ctx.put("requestURI", route.getPath()); // this is always ""
    ctx.put("proxy", route.getId());
}
...
```
I am encouraged that we seem to be converging on why my case differs from what you are expecting. I think what I am doing will need to be supported.

**Comment by spencergibb** [comment]
I am not saying "that Zuul only supports calling services by id that exactly match a route entry".

> We struggled to try to get path info in the target url, but never succeeded, finally making the discoverable services support being called with no path (we were constrained to not add path components to the incoming url for backwards compatibility with a system we are replacing).

Your custom code doesn't set the path. We expect the path to be set.

**Comment by bryan-helm** [comment]
My custom code does not determine anything but the service id to ask the RouteLocator for. How could I set the path on route entries that are added dynamically via service discovery? I never figured out a way to do that. How do you set the path in general, assuming it does NOT come from the incoming url? There is no way to specify it as part of service registration, so it cannot be coming via discovery. Comments in my code from earlier efforts indicate that setting a value in the context for "requestURI" other than "" resulted in a "Host cannot be null" error, although I have not tried that approach for SR6. It is certainly possible that I am overlooking something obvious, so please enlighten me if that is the case.

**Comment by spencergibb** [comment]
I always see a path set on routes coming from service discovery.

I don't know what else to do without seeing something that recreates this.

**Comment by bryan-helm** [comment]
Do you have a case where the service being discovered does not have an explicit entry in the routing configuration to match an incoming url?

**Comment by bryan-helm** [comment]
Where does the path you see in the discoverable service route entry come from? I tried doing the equivalent of `zuul.route.service-vendor.path=/foo` for the example above, and I still get "" for the path in the Route instance returned by RouteLocator for `routeLocator.getMatchingRoutes("service-vendor");`. So, even having an explicit entry in the route configuration did not give me a path for the discoverable service Route.

**Comment by bryan-helm** [comment]
FWIW, I have confirmed with a patch jar that your change above fixes the issue for my scenario in Brixton.SR6.

**Comment by spencergibb** [comment]
I'd like to fix the empty uri

**Comment by bryan-helm** [comment]
I don't think the empty uri is broken, necessarily. The application information that comes back from the discovery server does not include a path. It would make a lot more sense if it did, to have a true router that takes any incoming url and routes it to any outgoing url, with the path being specified by the server registering with the discovery server, but as it is today, that is not the case. So, whatever path information you are seeing has to do with the incoming url, not the service being called. How would you handle the case where the server you are routing to does not take any uri path? In my case I had no choice, as I found no way to include any path info for the target server that did not involve changing the incoming url, and that was not something I was allowed to do. Until the SR6 release, this has worked fine.

Even if there was a non-empty uri, I don't really see how that would solve this problem in general. The issue looks to be that in the middle of a call to put the server host and port in the "original" URI ("" in my case, something else in yours, the matched incoming request URI, I think - does it have a host and port already in your case? Is it the edge server host and port?), the code puts the scheme into the uri builder and creates a URI without the host and port, even though the host and port were passed in. That seems wrong regardless of how I got there. Your check that the raw path is empty before adding the host and port to the builder makes this change safe, since it will have no effect in the (normal) case where there is already a URI with the wrong host and port that will be changed after the updateToHttpsIfNeeded method returns.

The key point in my reproduction scenario is that the service id of the route that matches the incoming url is not the service id of the route I set up for the RibbonRoutingFilter to go to. Is there some reason I don't understand to require that the incoming url and target service id be part of the same route (other than this URI problem)? If that is the case, then our need to handle calls to multiple service ids that use the same incoming url will not be possible on versions past Brixton.SR5, unless we deploy your patch.

Thanks so much for your attention, I do appreciate the amazing work that has gone into the Spring Cloud ecosystem.

**Comment by spencergibb** [comment]
> The application information that comes back from the discovery server does not include a path.

That's not where the missing path is coming from, it comes from zuul matching the request to a path.

I'd be happy to continue looking at this if you can provide a sample application that recreates the problem.

**Comment by bryan-helm** [comment]
Sorry to confuse the issue with my speculation on what would make more sense to me. I understand the missing path came from the route matching the incoming url, and in my case, that path is associated with  a service id other than the one I then pass in to RibbonRoutingFilter via the context "proxy" attribute.  I am trying to decide what I can give you to illustrate this problem. It requires an edge server with an additional filter that looks up a route by a service id that matches a discoverable service, while the incoming url is mapped to a route with a different service id.  Do I need to give you the edge server and service code, or would the filter be enough?

**Comment by ryanjbaxter** [comment]
The best case scenario would be giving us everything we need to reproduce the problem.

**Comment by bryan-helm** [comment]
I know that, and I will spend the time to do it if I have to, but let me try one last appeal to reason. We have been using Spring Cloud from Angel.SR4 to Brixton.SR5, and we could always create a ZuulFilter where we include `@Autowire RouteLocator routeLocator;` and then call `Route route = routeLocator.getMatchingRoute(serviceId);` with serviceId being the registered name of a discoverable service, but not a name associated with an incoming url in Zuul configuration. This is a distinct case from the one you are familiar with, where PreDecorationFilter calls `routeLocator.getMatchingRoute(requestUri)` and gets a route that has a path matching the incoming request. In this case `route.getPath()` returns "", but that was ok, until Brixton.SR6. Now it fails in RibbonUtils.updateToHttpsIfNeeded as discussed here extensively.

If needed, I will be providing you with a generic Zuul server with the described filter, and a HelloWorld service for it to fail to route to (the service has to be running and be discovered before the failure occurs). Do you really need all that? Or is understanding that it is a different case than what you can create with the default Zuul filters, and that route.getPath() == "" is ok in this case, enough to agree that when it is "", then we shouldn't fail updateToHttpsIfNeeded with an exception?

**Comment by george-smith** [comment]
Spencer, I'm a little confused here. If you have a patch that will fix something that broke between SR5 and SR6, other than saying that you might want to also find root cause, and fix it there. What would be the reason to not commit the fix? That doesn't prevent you from finding root cause. It just fixes the break in SR6 vs SR5.

Just curious. I know that you're a reasonable guy :-)

**Comment by bryan-helm** [comment]
Another difficulty in providing a test case is that the discoverable service has to be running securely (`ribbon.IsSecure=true`), which means certificates and trust stores have to be provided. If I give you the edge server and filter, can you run your own Eureka instance and some other secure service locally with spring.application.name 'hello-service'? My code will then attempt to route to it (and fail under SR6).

**Comment by spencergibb** [comment]
that's fine.

**Comment by bryan-helm** [comment]
It turns out you do not have to actually set up a secure connection - having the hello-service running and having the edge server with `ribbon.IsSecure=true` is enough, since we don't make it to the actual service call. So, the attached .zip has 3 projects, an Edge Server, a Eureka Service, and a Hello World service. This was created on Windows, and includes a `buildAndRun.cmd`
[ZuulRibbonBug1099.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/584285/ZuulRibbonBug1099.zip)
 to build and run the 3 applications. Hitting `http://localhost:7000/whatever` will demonstrate the bug in the Edge Server cmd console. There is a readme.txt documenting what to do.

**Comment by bryan-helm** [comment]
Having this test case I was able to experiment to find other workarounds. Despite comments in my code that say it did not work in some earlier version of Spring Cloud, this is a workaround in the attached test case: In the filter, set the requestURI to "/":
```
            ctx.put("requestURI", "/");
```
In the test case, it was being set to route.getPath() which was "". When set to "/", the exception in toUri() does not occur. Note: the test case still fails unless the hello-service is running securely - I get exceptions about not using https. But that means it got past the previous point of failure.

This test case now succeeds without the code change to RibbonUtils:
```
@Test
public void testUpdateToHttpsIfNeededEmptyUri() throws Exception {
    IClientConfig config = mock(IClientConfig.class);
    when(config.get(CommonClientConfigKey.IsSecure)).thenReturn(Boolean.TRUE);
    URI uri = RibbonUtils.updateToHttpsIfNeeded(new URI("/"), config, new DefaultServerIntrospector(), new Server("localhost", 443));
    assertThat("No exception, uri now has https", uri, equalTo(new URI("https:/")));
}
```
It was apparently not the lack of host and port, but having https: with no / that caused the problem. Of course, I am not saying that I agree that throwing an exception when "" is passed in is the correct behavior. But just changing it to / might do the trick. Not sure why Server is being passed into updateToHttpsIfNeeded anyway.

Thanks again for your attention! The Spring Cloud community is fast moving and responsive. I appreciate your help.

**Comment by bryan-helm** [comment]
To be clear, setting the "requestURI" in the context to a value other than "" does NOT result in what you put in there actually being used in the uri for the Ribbon call to the discoverable service. Nothing lets you set that arbitrarily as far as I can tell. But it does get past the issue introduced in SR6. I have confirmed it also works in Camden.SR2.

**Comment by cah-andrewfitzgerald** [comment]
@spencergibb running into a similar issue using consul discovery when trying to proxy to a downstream https service.
If `ribbon.isSecure=false` zuul blows up due to an empty response (as expected).
If `ribbon.isSecure=true` it fails with the exact same `URISyntaxException` which is caused by a blank URI being passed in.

Both settings show the correct ip address in the logs
```
ClientException: Number of retries on next server exceeded max 1 retries, while making a call for: 10.10.....
```

The project it's running in is very simple.
```
@EnableZuulProxy
@SpringBootApplication
public class SomeApplication {

    public static void main(String[] args) {
        SpringApplication.run(SomeApplication.class, args);
    }

}
```
```
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: secret

spring:
  cloud:
    consul:
      host: ${host}
      port: 8500
      discovery:
        enabled: true
        register: false
        register-health-check: false

zuul:
  routes:
    watcherUi:
      path: /watcher-uil/**
      serviceId: watcher-ui

ribbon:
  IsSecure: true
```
```
buildscript {
	ext {
		springBootVersion = '1.4.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath('se.transmode.gradle:gradle-docker:1.2')
	}
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'docker'

jar {
	baseName = 'app'
	version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
}


dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-zuul')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.cloud:spring-cloud-starter-consul-discovery')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Camden.SR2"
	}
}
```

**Comment by sumanthculli** [comment]
@spencergibb , wanted to know if there a resolution available to this issue? , i am still facing this , zuul is  trying to call the micro service application(https) but getting the exception as @Jacuo

**Comment by bryan-helm** [comment]
Did you try the `ctx.put("requestURI","/");` workaround?

**Comment by sumanthculli** [comment]
thanks @bryan-helm this workaround helped in resolving this, i missed doing it earlier.

**Comment by ryanjbaxter** [comment]
@bryan-helm or anyone else, have you tried reproducing this with Edgware.SR4?  I cannot reproduce the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
