### ISSUE TITLE
Separate environments with single eureka server

### ISSUE THREAD

**Issue by paulvitic** [spring-cloud/spring-cloud-netflix#1185]
We would like to manage separate microservice environments with a single Eureka service discovery server. Is this possible? Could we use eureka.environment property for services and clients for this purpose?

**Comment by ryanjbaxter** [comment]
I guess the question is what do you mean by "manage"?  By "environments" do you mean dev, test, production?  Or do you mean different apps all together?

**Comment by paulvitic** [comment]
What I mean is, is it possible for a set in service instances to register themselves in lets say testing1 environment and another set of same type of service instances to register themselves in testing2 environment in the same discovery server instance. A client in testing1 environment only receives the socket address of a service instance registered in testing1 environment and not the same type of service instance registered in testing2 environment.

**Comment by ryanjbaxter** [comment]
OK I understand what you are saying now.

The only way I know how you could separate environments using a single Eureka service would be to use some kind of name convention when the service registers with Eureka.  For example all instances of service `xyz` in dev would register with `xyz_dev`.  In production they would register with `xyz_prod`, etc.  

I did a quick Google search as well and found [this discussion](https://groups.google.com/forum/#!topic/eureka_netflix/y15PqcNDHFM) in the Eureka Google Group where someone asked a similar question.  Sounds like the best way to approach the problem is to have separate Eureka servers fir each environment.

**Comment by paulvitic** [comment]
OK thanks.
