### ISSUE TITLE
Zuul double encoding issue in RibbonClientConfiguration

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [spring-cloud/spring-cloud-netflix#1241]
We just tracked down an issue where zuul was encoding urls twice.

When a request passes through either `RibbonRoutingFilter` or `SimpleHostRoutingFilter`, `ProxyRequestHelper::buildZuulRequestURI` is called, encoding the request.

Later in the request, the uri passes through `RibbonClientConfiguration.OverrideRestClient::reconstructURIWithServer` and is potentially encoded again, escaping characters that have already been escaped.

**Comment by cah-oster** [comment]
The problem appears in https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/RibbonClientConfiguration.java#L202 The code seems to be trying to change the scheme to "https" if the target scheme is not https but the server is configured to be secure.  The problem is the code is calls build(), which internally calls build(false) indicated the URL is not endcoded.  In this flow at least, the URL is already encoded so it ends up double-encoding it.  The other problem, in the this flow, is the URL is actually only a path so the call effectively does nothing except double-encode, as the scheme is null and remains null after the call.

It seems like the if block should only call the builder if the scheme is not null, and if it does call, it should call build(true);

**Comment by ryanjbaxter** [comment]
@cah-oster thanks for the analysis, maybe you would like to submit a pull request for your suggested fix?

**Comment by jebeaudet** [comment]
Using .build(true) won't encode the url but `UriComponents` will verify that the url does not contain any invalid character. We ran into this issue with a '+' in a query string IIRC https://jira.spring.io/browse/SPR-10172. 

We fixed it in our internal branch by reconstructing an URI with the plain old URI class in the end : https://github.com/coveord/spring-cloud-netflix/commit/a0ac405ac81c0e7d0b7369f8565c8a835a1ce3c9.

**Comment by cah-oster** [comment]
@jebeaudet Right, my point was at least in this flow, the URL is already encoded.  I'm not sure if that's true in all the other incoming flows (e.g. URL-based routes).  When I get a few mins I'll try to whip up a patch.  Minimally we can expose the boolean as a parameter to the reconstructURIWithServer method.

**Comment by jebeaudet** [comment]
You were right indeed, I just wanted to point out the limitations of `UriComponents` here.

At this point, I'm pretty sure the URI is always encoded since it's one of the last step before sending the actual request to the backend. We are running a big application composed of many microservices all in https and we haven't run into any issue yet with the commit I mentioned (who never encode the uri at this point).

**Comment by cah-oster** [comment]
For us we were able to short circuit this without code changes to spring by adding this bean:

 ```
@Bean
    ServerIntrospector serverIntrospector(){
        return new ServerIntrospector() {
            @Override
            public boolean isSecure(Server server) {
                return false;
            }

            @Override
            public Map<String, String> getMetadata(Server server) {
                return new HashMap<>();
            }
        };
    }
```

The DefaultServerIntrospector assumes any port ending in 443 isSecure (and thus trips this double encoding).  We are setting the communication to be https by specifying it in ribbon configuration, so this scheme transformation is unneeded.

`ribbon:
  IsSecure: true
`

**Comment by cah-oster** [comment]
Here's the pull request @ryanjbaxter 
https://github.com/spring-cloud/spring-cloud-netflix/pull/1244

I misspoke early about scheme change to https not doing anything when the scheme is null. That works fine as is, so the only change I made was to pass in "true" to the call to build.  The tests I added failed until I made that change.

**Comment by jebeaudet** [comment]
Maybe I wasn't clear before in my comment, using `UriComponents` build(true) method leads to a verification of the url so that no illegal character is in the URI. This longstanding issue is troublesome and I'm sure will lead to another issue opened: https://jira.spring.io/browse/SPR-10172. 

I've added a failing test here https://github.com/coveord/spring-cloud-netflix/commit/58b8efd9a90d92a0681e5a8788a2844100f93522 : 
```
Tests in error:
 testNotDoubleEncodedWhenSecure(org.springframework.cloud.netflix.ribbon.RibbonClientConfigurationTests): Invalid character '+' for QUERY_PARAM in "1+2"
```
Our fix is not the most compact but it does not have this limitation.
```
new URI("https", original.getUserInfo(), original.getHost(),
						original.getPort(), original.getPath(), original.getQuery(),
						original.getFragment());
```

**Comment by ryanjbaxter** [comment]
@jebeaudet if the fix did not address your specific issue than open another issue describing the problem
