### ISSUE TITLE
what it the relationship about timeout between ribbon and hystrix

### ISSUE THREAD

**Issue by aximo** [spring-cloud/spring-cloud-netflix#1324]
what it the relationship about timeout between ribbon and hystrix? I know this codes will create a RestClientRibbonCommand which extend from HystrixCommand:
`
org.springframework.cloud.netflix.zuul.filters.route.RestClientRibbonCommandFactory.create(RibbonCommandContext)
`

but, if I set
`
hystrix.command.default.execution.timeout.enabled=false
`
it seems that it doesn't take effect.
I also notice that there are some timeout configurations in 
```
com.netflix.client.config.DefaultClientConfigImpl.loadDefaultValues()
ReadTimeout
ConnectTimeout
ConnectionManagerTimeout
```

it seems that these configurations in DefaultClientConfigImpl take place even if hystrix.command.default.execution.timeout.enabled set to false.

so, my question is , what the relationship between these timeout configurations?

how cloud i disabled global timeout feature for the benefit of debuging?

thanks for any comments

**Comment by ryanjbaxter** [comment]
I agree that timeouts become quite confusing when both Ribbon and Hystrix are in play.  Each feature has its own timeout configuration so you need to configure them both in order to get the behavior you want.  For example this is a configuration that you might want to use in order to extend the timeout of both Hystrix and Ribbon:
```
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
```

**Comment by aximo** [comment]
get it,thanks @ryanjbaxter
