### ISSUE TITLE
Use RibbonClientConfiguration as default for configuration in @RibbonClient

### ISSUE THREAD

**Issue by ktong** [spring-cloud/spring-cloud-netflix#1340]
Currently, if wants to config Ribbon with @RibbonClient, it has to set configuration of @RibbonClient and RibbonClientConfiguration is suitable for most of it. So setting RibbonClientConfiguration as default for configuration in @RibbonClient makes code simple as @RibbonClient("foo")

**Comment by ryanjbaxter** [comment]
I am not sure I am following what you are saying, can you be more concrete?  Maybe using some code examples?

**Comment by ktong** [comment]
here is PR https://github.com/spring-cloud/spring-cloud-netflix/pull/1342

**Comment by spencergibb** [comment]
`RibbonClientConfiguration` is already the default.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/SpringClientFactory.java#L41 which specifies it as a default.

**Comment by ktong** [comment]
@spencergibb With this default, @RibbonClient("foo") should read server list from configuration **foo.ribbon.listOfServers**. However, it says **No instances available for foo** due to empty server list (it has two servers configured for **foo.ribbon.listOfServers** ). By the way, I use zookeeper service-discovery, so it also has another default from RibbonZookeeperAutoConfiguration

**Comment by spencergibb** [comment]
If you include zookeeper or eureka or consul, those become the default server lists. #927 supports setting `NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList` and then your list of servers.

It's helpful when creating an issue to tell us why you want or need something rather than telling us what to change. Your comment you just left is what you should have started with.
