### ISSUE TITLE
Feign/Ribbon throw Exception when spring.application.name has special character

### ISSUE THREAD

**Issue by 924060929** [spring-cloud/spring-cloud-netflix#1483]
I write a spring-cloud application with config 'spring.application.name=应用权限服务'.

The problem is Feign invoke 'URI uri = new URI("http://应用权限服务")', then 'uri.getHost()', it will return null because the string has special character.

I think appname cound be any string so that more human, can you replace the real uri before create URI instance? :)

**Comment by ryanjbaxter** [comment]
I could see how this might be an issue, but I am unclear how the application name effects the URI created by Feign.  The two are independent of each other.  Can you provide a sample application?

**Comment by 924060929** [comment]
@ryanjbaxter sure, I will product a simple program at this weekend

**Comment by 924060929** [comment]
@ryanjbaxter Here is the code.
eureka-server: [https://gist.github.com/924060929/96c14b7f3dc9c8496817f6898ad23051](url)
eureka-client: [https://gist.github.com/2f294773b6e604eaa04ff47bd0381c11](url)
feign-client: [https://gist.github.com/a068aebef26f049b7502b7fe8cc7fa7e](url)

If you want to quikly look the exception, run feign-client without eureka-server and feign-client, because the exception throw when feign-client startup. 
In feign-client, the com.example.Main use Spring-cloud-Feign to send a request to eureka-client.
Please help me. : )

**Comment by ryanjbaxter** [comment]
OK now I understand better what is happening, thanks for the sample.

I think we validate the Feign Client name to make sure it is a valid host name because we are going to use Ribbon to then make the request to the service id with that client name.  Ribbon works by looking up the service with a url of `http://<client name>`.  If client name is not a valid host name I would imagine we would run into issues.

This is just a guess though, maybe @spencergibb can shed more light on this.

**Comment by spencergibb** [comment]
Service id and feign need to valid URL's because of the way feign works. You'll have to change your service id or not use feign.
