### ISSUE TITLE
Consider use of Guava

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-netflix#154]
I've heard that guava have been known to break back compatibility between releases, this can cause problems if the version that Spring Cloud uses differs to the one the the user wants. It might be worth considering if it's really needed or if the Spring `Utils` classes might work instead.

**Comment by dsyer** [comment]
AFAIK we don't use guava, but Netflix does internally so we are forced to include it as a dependency.  Where did you see it being used?

**Comment by philwebb** [comment]
I mainly noticed its use in `spring-cloud-netflix`:

https://github.com/spring-cloud/spring-cloud-netflix/search?utf8=%E2%9C%93&q=com.google&type=Code

**Comment by jvalkeal** [comment]
Yeah, guava is a major pain particularly in hadoop umbrella. There are 3 main versions out there where the oldest is about 5 years old. Guava is know not to care that much about backward compatibility and project simply removes methods or does something else which breaks things up.

IMHO, any kind of foundational framework should stay away from guava. i.e hadoop cannot change those 5 years guava libs because existing user apps would break. Some other newer projects like spark is already using recent guava libs which don't work with the version from hadoop. This is difficult for user because whatever he does, things are pretty much guaranteed to go south.

We should stay away from guava but at least we can then "blame" netflix if user complains. Maybe netflix could fork/bundle(with a different package) needed guava stuff within their own libs? Hadoop guys have talked about this option to fix the guava mess in their stuff.
