### ISSUE TITLE
boot upgrade to httpclient broke SimpleHostRoutingFilter if content type charset is used

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1649]
See https://jenkins.spring.io/job/spring-cloud-netflix-master-ci/1799/

Maven deps
```
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.5.2:compile (version managed from 4.5.1 by org.springframework.boot:spring-boot-dependencies:1.5.0.BUILD-SNAPSHOT)
[DEBUG]          org.apache.httpcomponents:httpcore:jar:4.4.6:compile (version managed from 4.4.4 by org.springframework.boot:spring-boot-dependencies:1.5.0.BUILD-SNAPSHOT)
```

**Comment by hartmut-pq** [comment]
Hi, I've got same issues with 1.2.5.RELEASE

**Comment by miosman** [comment]
The fix for 1.2.5.RELEASE splits the contentType string on ";charset=" which fixes the issues partially. Some clients send an extra space between the semi colon and the charset e.g. "; charset=" and as such the bug persists in 1.2.5.RELEASE. #1664 fixes the issues with such clients.

Is there any plans for that fix to be backported into 1.2.x? As due to this bug we had to revert back to spring  boot 1.4.3.

**Comment by spencergibb** [comment]
@miosman already done https://github.com/spring-cloud/spring-cloud-netflix/commit/ee953bef07034f88e352a7ebf938cbd345e2535e

**Comment by hartmut-pq** [comment]
@miosman -> #1663 waiting for Camden.SR6 release, too...
