### ISSUE TITLE
Zuul server occasionally becomes unresponsive because of lots of tpc connections in close_wait state

### ISSUE THREAD

**Issue by ltebean** [spring-cloud/spring-cloud-netflix#1979]
We are using Zuul as the api gateway, and we found that the server will occasionally be unresponsive because hundreds of tcp connections are in close_wait state(which are not correctly cleaned by the server). We are using `spring-cloud-starter-zuul 1.2.7-release`, and `zuul-core 1.3.0`. We suspect it's a bug in zuul, can you help to debug the problem, thanks!

**Comment by ryanjbaxter** [comment]
Might be related to #1970.  What version of Spring Cloud are you using?

**Comment by ltebean** [comment]
The spring clound version is `Camden SR7`

Our request flow is:
 ```
 load balancer -> zuul -> service
```
the close_wait connections is between `load balancer -> zuul`, so I think it is different from the problem in #1970.

**Comment by spencergibb** [comment]
If that's the case, why do you think there is a problem with zuul?

**Comment by ltebean** [comment]
With netstat I see a lots of tcp sockets in CLOSE_WAIT status, the local address is the zuul server and the foreign address is load balancer. So I assume this means the client (load balancer) has just terminated the connection and the zuul server has not properly closed the connection at its end.

**Comment by ryanjbaxter** [comment]
Could also be related to #1785 but that should be in `Camden.SR7`.  Could you update to `Dalston.SR1` and see if you see the same thing?

**Comment by ryanjbaxter** [comment]
@ltebean I think this could be related to #1970 since we are not closing the connections.  Do you have Spring Retry on the classpath?  Are you retrying specific response codes?

**Comment by kupci** [comment]
I was curious about the fix for [#1785 ](https://github.com/spring-cloud/spring-cloud-netflix/issues/1785) after reading the documentation for [http keepAlive](https://docs.oracle.com/javase/8/docs/technotes/guides/net/http-keepalive.html). As Dave Bender has noted in issue [1997](https://github.com/spring-cloud/spring-cloud-netflix/issues/1997), there are a few issues and fixes, however we are still running into the problem, perhaps due to slightly different environment/configuration (we use jetty, etc), we have been unable to resolve the issue, though it seems very similar to the issues described here (1979) and the others.

Specifically, in the finally block of the [writeResponse ](https://github.com/pway99/spring-cloud-netflix/blob/86139394766f4e04049313ff4491c401750a3c80/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java) method of SendResponseFilter, there is a try-catch. If I/O exception, there is only a line to log the message. 

		catch (IOException ex) {
				log.warn("Error while sending response to client: " + ex.getMessage());
		}

How does this handle 404s, where an error stream is opened? For example, shouldn't the code be something similar to the keepAlive documentation, and attempt to close the errorStream? 


Here's what the Oracle doc says:

What can you do to help with Keep-Alive?

1. Do not abandon a connection by ignoring the response body. Doing so may results in idle TCP connections. That needs to be garbage collected when they are no longer referenced.
2. If getInputStream() successfully returns, read the entire response body. 
3. When calling getInputStream() from HttpURLConnection, if an **IOException occurs, catch the exception and call getErrorStream() to get the response body (if there is any)**.


Of course, in writing this out here, it occurs to me,  that we should be able test this out as we are currently restarting our Zuul instances every few hours.

**Comment by ryanjbaxter** [comment]
@kupci potentially.  Are you just pointing out one spot where we could not be closing the connection successfully or is this specifically where you think you are running into an issue?

**Comment by kupci** [comment]
This is one of the possibilities, we haven't proven anything yet. Dave Bender is setting up a test environment, plain vanilla Zuul, so we can try out some ideas without impacting users.

**Comment by ryanjbaxter** [comment]
OK I am going to close this issue for now.  Once you have more information please reopen this issue or create another one so we can address this.  We appreciate your analysis!
