### ISSUE TITLE
Debug Logs:Cleared thread-bound request context

### ISSUE THREAD

**Issue by harishkadamudi** [spring-cloud/spring-cloud-netflix#2036]
[sample.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/1067952/sample.txt)

Have configured Eureka Server in a Standalone mode and I have enabled Spring Security and Have couple of Clients connecting to it.
Clients are successfully able to connect to Eureka Server, When I look at Eureka Server logs I see lots of Log being logged, like 16:57:31.538 **[http-nio-8846-exec-9] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Bound request context to thread: org.apache.catalina.connector.RequestFacade@1a23671d
16:57:31.540 [http-nio-8846-exec-9] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@1a23671d**

What are these?

Have attached sample logs along with this ticket. Would like to know Is that something I a missing to configure or Should i turn off simply.

This is a concern as file Log file size is growing rapidly.

Thanks

**Comment by harishkadamudi** [comment]
When i forced Eureka Clients to shutdown, I see no such Logs being logged after that.

**Comment by ryanjbaxter** [comment]
`OrderedRequestContextFilter` is a class from Spring Boot.  I am unsure what it is doing, but you are probably seeing that logging because the Eureka Clients will send a heartbeat request to the server every so often.  Disabling debug level logging will stop the logs from being printed.  If you have more questions about what `OrderedRequestContextFilter` does I suggest you ask that question in the Spring Boot repo.

**Comment by waddwaw** [comment]
你检查下你的端口号 是否被占用 一般来说是有人在请求你的接口导致的
