### ISSUE TITLE
Reload Custom Routing Logic in Zuul Filter without restarting ZUUL

### ISSUE THREAD

**Issue by sri420** [spring-cloud/spring-cloud-netflix#2037]
I am able write a ZUUL filter to do custom routing based one or more request parameters in request and then route to the target downstream service by setting the serviceId of the target service in RequestContext. This is for a requirement where I need to choose from one of the 3 downstream services based on the request parameters.

With this approach, whenever I have to add a new custom routing or make changes to an existing custom routing logic in the ZUUL filter I have to make changes to zuul code , build it and then eventually recycle the zuul service. This impacts the traffic for all other services for which the custom routing logic does not apply.

I am looking for a better way do custom routing or reload the custom routing logic , without restarting zuul, perhaps by externalizing the custom routing logic in the zuul filter as a configuration . I am not sure, if its possible, because the logic is written in Java in zuul filter which must to be compiled and built every time. So, restarting zuul is inevitable.

Is there a simpler and effective approach for my requirement.

**Comment by ryanjbaxter** [comment]
The first thing that comes to mind is to make the Zuul proxy highly available and roll out deployments of the proxy when new versions come available so that brining down the app is not an issue.

Without knowing more details about the routing requirements it is hard to make suggestions for another approach.  Keeping routing logic in configuration is always idea so that way you can change the configuration without having to deploy a new version of the application, but it sounds like the routing logic you need in place is a bit more complicated than that.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
