### ISSUE TITLE
Eureka+ Ribbon Load Balancer

### ISSUE THREAD

**Issue by harishkadamudi** [spring-cloud/spring-cloud-netflix#2062]
This is not an Issue, opening this one for clarification.

I have Service Discovery Eureka Set up and I want Zuul as API Gateway, and I want to achieve load balancer.

I have copied below code from spring-cloud documentation site along with the explanation.

**with Eureka**
application.yml
 zuul:
  routes:
    users:
      path: /myusers/**
      url: http://example.com/users_service

_documentation link_

http://cloud.spring.io/spring-cloud-static/spring-cloud.html#netflix-zuul-reverse-proxy

_These simple url-routes don’t get executed as a HystrixCommand nor can you loadbalance multiple URLs with Ribbon. To achieve this, specify a service-route and configure a Ribbon client for the serviceId_

I am finding it hard to understand above statement, I would like to use Eureka, and I want my Rest Template to be Load Balanced.

Is it only saying you can't use multiple URLs, however one can provide single URL and can be load balanced.

In my Eureka Client, I have below code

        @LoadBalanced
	@Bean
	RestTemplate restTemplate() {
		return new RestTemplate();
        }

**Comment by ryanjbaxter** [comment]
I am a little confused by your question because your concern about Zuul and using `@LoadBalanced` `RestTemplate`s do not have anything to do with each other.  Here is some clarification on your question about Zuul.

It basically means that when you configure a route in Zuul using the `url` property neither Hystrix of Ribbon will be used.  If you are using Eureka you won't need to specify the `url` property for the route and by default Zuul will use bother Hystrix and Ribbon.  

When using Eureka you can also use a `LoadBalanced` `RestTemplate` which will use Ribbon, but will not use Hystrix.

Does that help?

**Comment by harishkadamudi** [comment]
@ryanjbaxter ,

Thanks.
