### ISSUE TITLE
forward proxy problem

### ISSUE THREAD

**Issue by xyrc** [spring-cloud/spring-cloud-netflix#2068]
```
if (ctx.containsKey("forward.to")) {
    return null;
}
```
Code excerpt from `org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping.lookupHandler` at line 87-89
Why do you return null when RequestContext contains "forward.to" ?
returning null causes forward proxy to follow the request, ZuulHandler is not found,
This can cause forward to zuul local services not available.

so, i want remove "forward.to" from RequestContext In a custom SendForwardFilter,  I'm not sure if it will cause other problems.

**Comment by spencergibb** [comment]
Can you explain what you are trying to accomplish rather than specific symptoms?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by spetsov** [comment]
I have the same issue, could you please explain why this null check is required?
What I'm trying to achieve is to rewrite all urls, for example:
routes:
    foo:
      path: /foo/**
      url: forward:/bar
    bar:
      path: /bar/**
      serviceId: bar

This way if I request /foo/id/123, it will forward to /bar/id/123 and then this will be handled by the Zuul filters through the service discovery. However, at the moment, because of that null check, I'm getting a No handler mapping found for from ZuulHandlerMapping. I tried removing that key from the context and it seems to be working without a problem.

**Comment by spetsov** [comment]
@spencergibb
There’s no exceptions, I’m just seeing that with trace enabled in the logs. What’s basically happening is:
1. My forward to mapping is detecting a valid request
2. The request reaches the Forward Zuul filter.
3. The filter forwards and the request goes back to ZuulHandlerMapping
4. Because “forward.to” was set by the PreDecorationFilter, the ZuulHandlerMapping now goes into the if mentioned above and returns a null
5. As a result I get a 404, even though the forwarded to path does exist in the routes and if I request it on its own everything works fine

I suppose that the Forwarding feature was not meant for this use case, but I don’t see why it cannot be enabled. Are there any concerns for the request looping back through all the Zuul Filters after a forward?
