### ISSUE TITLE
ConfigRefreshTests fails

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#2310]
expected 3, actual 1

**Comment by ryanjbaxter** [comment]
Looks like something is messed up with auto service registration.  Since the `AutoServiceRegistrationProperties` is not created the `EurekaAutoServiceRegistration` bean is not created.  When that bean exists it will call `EurekaClient.getApplications` when the application starts and when the application is refreshed.  Might have something to do with #2242.

**Comment by spencergibb** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-commons/commit/1829d370bad904ef59185d938367641e6c8c4513
