### ISSUE TITLE
How to disable request decompression forwarded to downstream systems

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#2389]
This is continuation of question from https://stackoverflow.com/questions/46736324/zuul-ribbonroutingfilter-content-encoding-gzip-response

**Comment by ryanjbaxter** [comment]
This should be addressed in Edgware since we centralized how the Apache HTTP Client is created. 
https://github.com/spring-cloud/spring-cloud-commons/blob/a30d24083dd5155b7d22219b5951e0f1555429a8/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientFactory.java

**Comment by sureshkrishnamoorthy** [comment]
@ryanjbaxter
Please let me know if this will address the service id based routing ie RibbonLoadBalancingHttpClient as well ?

**Comment by spencergibb** [comment]
@sureshkrishnamoorthy why would it? please don't comment on closed issues. Please ask questions on https://gitter.im/spring-cloud/spring-cloud
