### ISSUE TITLE
What if I use zuul with okhttp, how to set connections?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#2527]
I'm using zuul with okhttp3.
I set 
`ribbon.okhttp.enabled: true` according to the doc <http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#_zuul_http_client> 
but When I dive into the code in 
`org.springframework.cloud.netflix.ribbon.okhttp.OkHttpLoadBalancingClient#createDelegate` 
I find code like below ：
```java
@Override
protected OkHttpClient createDelegate(IClientConfig config) {
    return new OkHttpClient();
}
```

SO, I wonder how to set MaxTotalConnections or MaxConnectionsPerHost

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud?

**Comment by eacdy** [comment]
Edgware.RELEASE

**Comment by eacdy** [comment]
@ryanjbaxter  ping...

**Comment by holy12345** [comment]
Hi @eacdy 
To my knowledge, the source code for creating `okhttp3 `has been refactored in Edgware.RELEASE compared to Dalston.SR4 (or earlier).
`okhttp `is now created in `OkHttpRibbonConfiguration`. If you do not involve retry then the specific method is `OkHttpRibbonConfiguration # retryableOkHttpLoadBalancingClient`().
The above procedure eventually calls the `AbstractLoadBalancingClient's` constructor, and here it should be noted that the constructor called in the version of Edgware.RELEASE is
```
protected AbstractLoadBalancingClient(D delegate, IClientConfig config, ServerIntrospector serverIntrospector) {
    super(null);
    this.delegate = delegate;
    this.config = config;
    this.serverIntrospector = serverIntrospector;
    this.setRetryHandler(RetryHandler.DEFAULT);
    initWithNiwsConfig(config);
}
```
The previous version is called:
```
protected AbstractLoadBalancingClient(IClientConfig config, ServerIntrospector serverIntrospector) {
    super(null);
    this.delegate = createDelegate(config);
    this.config = config;
    this.serverIntrospector = serverIntrospector;
    this.setRetryHandler(RetryHandler.DEFAULT);
    initWithNiwsConfig(config);
}
```
So I do not think there will be any problem description to you.
Another question is about `MaxConnectionsPerHost`
Because it is using the `ConnectionPool`, so I think we only need to set `MaxTotalConnections `on it, there is no `MaxConnectionsPerHost `this `ConnectionPool `internal parameters. `okhttp `internally places all request links in a queue, with a thread clearing expired connection
Above is my understanding, hoping to help you. Thank you.

**Comment by ryanjbaxter** [comment]
The OK Http Client is configured and created here https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpRibbonConfiguration.java

You can configure the max total connection by setting `ribbon.MaxTotalConnections`.

**Comment by holy12345** [comment]
Hi @ryanjbaxter 
Thank you for your reply, my understanding is correct? Also because we use `okhhtp`, so we do not seem to need to set `MaxConnectionsPerHost `this parameter.

**Comment by ryanjbaxter** [comment]
@holy12345 yes for the most part

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
