### ISSUE TITLE
Zuul in Edgeware.RELEASE does not redirect 302 through browser

### ISSUE THREAD

**Issue by hpeimer** [spring-cloud/spring-cloud-netflix#2578]
This issue was discussed in [Stackoverflow](https://stackoverflow.com/questions/47817427/zuul-returns-http-status-200-instead-of-302/47959430#47959430).

In Edgeware.RELEASE a redirect on the server-side should send HTTP status 302 to the browser. Instead the browser receives the new content and HTTP 200 status.

In Dalston.SR4 an HTTP 302 status is returned by the server, and the browser redirects.

**Comment by ryanjbaxter** [comment]
Can you provide your Zuul configuration?  Are you using service discovery or configuring the route URLs yourself?

**Comment by hpeimer** [comment]
Not using service discovery.

Here is the simple Zuul from the example, as seen on Stackoverflow

server:
  port: 8080
zuul:
  routes:
    core:
      sensitive-headers:
      path: /core/**
      url: http://localhost:9090/

**Comment by jcarvalho** [comment]
Hi. We're facing the same issue. This seems to have been introduced in commit `2aa93abc0f301a2e99e193c2f23eef2fdd306ad7`, in which a custom `RedirectStrategy` that was being manually registered went missing.

I can confirm that the issue is only present in `Edgware.RELEASE`, it's not present in Dalston `SR3` or `SR5`.

**Comment by ryanjbaxter** [comment]
Thanks.  `SimpleHostRoutingFilter` used to disable following redirects but since we centralized the creation of the client we lost that functionality.  
https://github.com/spring-cloud/spring-cloud-netflix/commit/2aa93abc0f301a2e99e193c2f23eef2fdd306ad7#diff-2e8235c4a9fe2136b17a43f6ff2f8080L264

Here is what the client creation looks like today.
https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java#L216

I submitted #2608 which I think will restore the original behavior.

**Comment by jcarvalho** [comment]
For completeness sake, shouldn't `.setRetryHandler(new DefaultHttpRequestRetryHandler(0, false))` be restored as well?

**Comment by spencergibb** [comment]
Retry and handling redirect are separate concerns no?

**Comment by jcarvalho** [comment]
Indeed, maybe a separate issue should be opened for that, should the need arise in the future?

**Comment by ryanjbaxter** [comment]
Yes a separate issue, but only if you can come up with a use case where it is needed.
