### ISSUE TITLE
Eureka SSL config and separate management port registering with wrong secureHealthCheckUrl

### ISSUE THREAD

**Issue by habbo656** [spring-cloud/spring-cloud-netflix#2673]
Hi,

we are using SSL configuration for our services and we have differing server.port and management.port.

Looking at how the instances are registered, the secureHealthCheckUrl seems to be wrong. It uses the server.port instead of the management.port. This only happens with ssl configuration. The problem does not occur without ssl.

```xml
<instance>
    <!-- ... -->
    <port enabled="false">10007</port>
    <securePort enabled="true">10007</securePort>
    <!-- ... -->
    <metadata>
          <management.port>11007</management.port>
    </metadata>
    <homePageUrl>http://localhost:10007/</homePageUrl>
    <statusPageUrl>http://localhost:11007/info</statusPageUrl>
    <healthCheckUrl>http://localhost:11007/health</healthCheckUrl>
    <secureHealthCheckUrl>https://localhost:10007/health</secureHealthCheckUrl>
    <!-- ... -->
</instance>
```
configuration:
```
server.port=10007
server.ssl.enabled=true
server.ssl.key-alias= ...
server.ssl.key-store= ...

management.port=11007
management.security.enabled=false
management.ssl.enabled=true
management.ssl.key-alias= ...
management.ssl.key-store= ...

eureka.instance.metadata-map.management.port=${management.port}
eureka.instance.nonSecurePortEnabled=false
eureka.instance.securePortEnabled=true
eureka.instance.securePort=${server.port}
```
The only workaround that works for me ist registering manually for each service the secure-health-check-url with hardcoded port, since SPEL expressions are not evaluated.

eureka-client-1.7.0
Spring-cloud version Edgware.RELEASE (also Dalston.SRx tested...)
spring-boot version 1.5.9.Release

**Comment by ryanjbaxter** [comment]
Which version of Spring Cloud are you using?

**Comment by habbo656** [comment]
Spring-cloud version Edgware.RELEASE (also Dalston.SRx tested...)

**Comment by ryanjbaxter** [comment]
Can you try Edgware.SR1?

**Comment by habbo656** [comment]
Still the same issue with Edgware.SR1

**Comment by ryanjbaxter** [comment]
So I have been looking into this issue and discovered something odd (no surprise).

If we look at the `getHealthCheckUrl` method in `DefaultManagementMetadataProvider`
https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/metadata/DefaultManagementMetadataProvider.java#L40

The health check url returned there should use `https` but as you have shown above it doesnt.  The reason is that `EurekaInstanceConfigBean.isSecurePortEnabled()` returns `false`.  This is because we don't set `isSecurePortEnabled` to true in `EurekaClientAutoConfiguration.eurekaInstanceConfigBean`.

If we fix that bug than the Eureka Client will register the health check URL using `https`.  So that leads me to the question of whether that is right or not?  Since we have the secure health check URL property should the health check URL property always be `http`?  What is the non secure port is disabled?  Then it would seem that the health check url and the secure health check url should both be `https`.  But if the non secure port is enabled should the health check url use http and the secure health check url use `https`?

@spencergibb @Aloren thoughts?

**Comment by Aloren** [comment]
Looks complicated to me 🤓 Maybe we should always set health url to http+app.port and secure health url to https+management.port? Client could then use needed property based on properties nonSecurePortEnabled and securePortEnabled values. 
Or could we check how this class was initialized in netflix libraries?

**Comment by spencergibb** [comment]
We've lost sight of the fact that these computed values are just defaults. You can set them to whatever value you want. We'll never be able to cover all possible values.

The other thing, these have no real meaningful use except for display in the dashboard. 

I'm off the opinion that we scrap all the logic and do nothing.

**Comment by Aloren** [comment]
I've found this [ticket](https://github.com/Netflix/eureka/issues/894).
As I understand original behavior was setting secure healthcheck url only if securePortEnabled is true. The non secure healthcheck url is never changed and is set to http+public port.

**Comment by ryanjbaxter** [comment]
> We've lost sight of the fact that these computed values are just defaults. You can set them to whatever value you want. We'll never be able to cover all possible values.

@spencergibb yes true, but our computed value is wrong ;)

I think a good middle ground is leave the functionality as is today, but at least set the secure health check url to the right value when `isSecurePort` is enabled.
