### ISSUE TITLE
Feign and Eureka - Load balancer does not have available server for client:

### ISSUE THREAD

**Issue by mgmike100** [spring-cloud/spring-cloud-netflix#2884]
Hi,

I am using Redhat Openshift as my container platform which is Docker and Kubernetes under the hood.  I have developed some services which I have deployed to Eureka and can call the externally facing rest services.  What I have a problem with is when I am trying to call an internal microservice from a microservice.  I believe I have not got the configuration correct.  I have tried different config but to no avail.  Can anybody help.

I am going to show the code and config below as screen shots so hopefully some can ID the error.  Many thanks

Eureka Server
![image](https://user-images.githubusercontent.com/38429728/39307139-f346280c-4959-11e8-9cf8-fc33d1ca13e3.png)

Eureka/Apps
![image](https://user-images.githubusercontent.com/38429728/39307079-c2679568-4959-11e8-842f-74a7545491b2.png)
![image](https://user-images.githubusercontent.com/38429728/39307105-d93abeaa-4959-11e8-8754-da04dd04ae08.png)

Conversion Service code and config
![image](https://user-images.githubusercontent.com/38429728/39307216-20673e5c-495a-11e8-84fd-2dbef2659f16.png)

![image](https://user-images.githubusercontent.com/38429728/39307238-3160e7bc-495a-11e8-8b09-501a36dcb78c.png)

Exchange Service and config

![image](https://user-images.githubusercontent.com/38429728/39307324-6dddbf4e-495a-11e8-93be-17d60ec7d700.png)

Openshift environment service and error
![image](https://user-images.githubusercontent.com/38429728/39307443-b50e6814-495a-11e8-980d-f37077551fa6.png)

Please help with my configuration as is driving me mad

![image](https://user-images.githubusercontent.com/38429728/39307405-9dd89e76-495a-11e8-991c-4f6cb451ad52.png)

**Comment by ryanjbaxter** [comment]
Screenshots are not very useful.

Typically situations like this are very hard to help with since it is something in your environment that is configured wrong.  Especially since I personally have no knowlege of OpenShift I cant even make any general suggestions.  All I can say is that the address registered in Eureka will need to resolve for the containers that are going to be making requests to that service.

**Comment by yangzhoucyl** [comment]
Please add configuration : 
eureka:
  instance:
    preferIpAddress: true

**Comment by eacdy** [comment]
@mgmike100 Maybe you Should change the code to like below.
`@FeignClient(name = "any name", url = "exchange-service.currency-conversion-service.svc")` ,because if you use only `name` attribute, feign will use name to search service in eureka server.

BTW, `@FeignClient(name = "currency-conversion-service")`  should work as well.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
