### ISSUE TITLE
Eureka Server Multi-Instance Issue in service Discovery

### ISSUE THREAD

**Issue by karthikrajakandasamy** [spring-cloud/spring-cloud-netflix#2994]
I have three Eureka server which is cluster each other. Let say Eureka1,Eureka2 and Eureka3. Now i register my service in Eureka1 for service Discovery. Then from another UI application i Call Eureka2 and Fetch the registered service URL, it will work because three servers are cluster. It was working fine for me.

The issue is, Now i stopped the Eureka1, then now i tried to fetch the registered service details in Eureka2 from UI application, it is throwing error. Because the service initially registered in Eureka1. Is there any configuration needed to solve this issue? Can any one help me to resolve this, thanks in advance.

**Comment by ryanjbaxter** [comment]
Is the service also configured to register with Eureka2 or just Eureka1?

**Comment by karthikrajakandasamy** [comment]
@ryanjbaxter  Thanks for your intrest. Actually the service Registered in Eureka 1, since it is cluster it is affected in Eureka 2 also. If the Eureka 1 is running, then i can able to fetch registered service details from Eureka 2 also. The issue is when i stop Eureka1, i could not fetch the details from Eureka 2.

**Comment by ryanjbaxter** [comment]
Probably because the service can no longer contact Eureka1, you should configure the service to register with all three Eureka servers so if Eureka1 is not reachable it will go to Eureka2 etc.  I believe you can do something like this
`eureka.client.service-url.defaultZone=http://eureka1/eureka/,http://eureka2/eureka/,http://eureka3/eureka/`

**Comment by karthikrajakandasamy** [comment]
hi @ryanjbaxter  i already used the above property which you mentioned, though it is not working.

**Comment by ryanjbaxter** [comment]
Yes but did you add all 3 eureka server urls?  If so can you provide a sample that reproduces the problem?

**Comment by holy12345** [comment]
@karthikrajakandasamy 

In my mind, if your client only configure one eureka server such as
```
eureka.client.service-url,defaultZone=http://eureka1
```
When eureka server1 is UP you can fetch all client information because , client will send heartbeat
to eureka server1 and eureka server1 will replicate the information to eureka2, so you can fetch information from eureka server2. if eureka server1 is DOWN(and your client not configure the eureka server2), then eureka server2 will not receive the replicate information from eureka server1 so, you can not fetch the information. 

So I think the best way is every client will configure the all eureka server.such as 
client configure:
```
eureka.client.service-url,defaultZone=http://eureka1, http://ureka2, http://eureka3
```
at above configure if eureka server1 is DOWN then your client will auto register itself information to eureka server2.

welcome communication : )

thanks

**Comment by skyofdust** [comment]
@karthikrajakandasamy is this still accurate?

If you put multiple eureka servers' addresses in default zone property and it is still not working, the problem might be that your eureka instances run on the same server and they share the same IP which you are using in combination with different ports to create urls which you put in the default zone property. Like this:
`eureka.client.service-url,defaultZone=http://localhost:8001, http://localhost:8002, http://localhost:8003`

If multiple instances of eureka servers are run on the same IP and they interconnected, each eureka instance might see the others as itself. In that case if you turn one instance off while there are services registered on it, services might be lost for a short time, untile they register on the another eureka host. So there is a short downtime if one eureka fails. Anyway, this is not normal behavior.

Try to create different hostnames for different eureka instance (the easiest way is to do that in hosts file), and change the defaultZone property:
`eureka.client.service-url,defaultZone=http://eureka-primary:8001, http://eureka-secondary:8002, http://eureka-tertiary:8003`

**Comment by ryanjbaxter** [comment]
Closing due to lack of feedback.  Please reopen if you still have issues.
