### ISSUE TITLE
Eureka shutdown BeanCreationNotAllowedException

### ISSUE THREAD

**Issue by xyydcoo** [spring-cloud/spring-cloud-netflix#3025]
version:  Finchley.RELEASE
![0ys2 oj p_zqts28n3h5my](https://user-images.githubusercontent.com/29936988/41840125-877efd8e-7897-11e8-8a64-a0e75e026cd9.png)

Is there a lack of dependence? After I have added the spring-boot-starter-web dependency, the service starts to be normal

**Comment by ryanjbaxter** [comment]
Screenshots are not very useful.  Please put the stacktrace in the issue and provide a project that recreates the issue.

**Comment by xyydcoo** [comment]
@ryanjbaxter  I offer a demo.
[finchley-service-consumer.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/2135176/finchley-service-consumer.zip)

**Comment by ryanjbaxter** [comment]
I think this error makes sense, we are trying to create a bean when the application is shutting down.

The application is shutting down because there is nothing keeping it running, ie no HTTP server for example.  This why you dont see the error when you put `spring-boot-starter-web` on the classpath.
In this case you will want some type of HTTP server running or else how else would your `RestController` get invoked.

**Comment by xyydcoo** [comment]
@ryanjbaxter  thanks, I've already understood what you mean.
