### ISSUE TITLE
[Question] Zuul dosen't support `content-encoding` header

### ISSUE THREAD

**Issue by jadetang** [spring-cloud/spring-cloud-netflix#3059]
I have an API proxied by Zuul. The client uses gzip to compress the HTTP message body. 
However, the downstream service complains about the format of the body, because the `content-encoding` header is not set by Zuul.  See details in this issue https://github.com/spring-cloud/spring-cloud-netflix/issues/3008

Does anyone have the same issue?

**Comment by mdiniz** [comment]
I have the same issue. I use version 1.3.X and as workaround, I add the `Content-Encoding` header to the Zuul request header if it is present on the incoming request. However, this workaround will stop working on v2.0.1 onwards because of pull request #3047 , which calls `isIncludedHeader` also on Zuul request headers, and this method removes `Content-Encoding`
@dev-priporov any thoughts?

**Comment by mdiniz** [comment]
Hi @dev-priporov 
#3047 doesn't cause the problem with `Content-Encoding`, but it will break the workaround I mentioned above.
As of now, if the request has `Content-Encoding`, it will be removed on the block starting at https://github.com/spring-cloud/spring-cloud-netflix/pull/3047/files#diff-1c057d0a3e3db3a002dac5d3b33b5c1cL132, because `isIncludedHeader` will return false. The workaround was to copy the `Content-Encoding` header to the Zuul request header in a separate filter (something like `ctx.addZuulRequestHeader("content-encoding", request.getHeader("content-encoding"))`). But with #3047 we call `isIncludedHeader` on the Zuul request headers as well, so it will be removed again.

**Comment by jadetang** [comment]
The workaround is not compatible with the latest version of Zuul, because  #3047 apply the `isIncludedHeader` method to ZuulRequestHeaders as well, which remove the `content-encoding` after your filter. @mdiniz
