### ISSUE TITLE
XStream: Illegal reflective access

### ISSUE THREAD

**Issue by melloware** [spring-cloud/spring-cloud-netflix#3315]
Spring Boot: 2.1.1
Spring Cloud: Greenwich.M3
JDK: OpenJDK 11.01

I am getting this error on startup using JDK11.

> 2018-12-10 13:56:24.447  INFO [mission-control,,,] 10804 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 21 endpoint(s) beneath base path '/actuator'
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/elefkof/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
> WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

It looks like an open XStream issue: https://github.com/x-stream/xstream/issues/101

**Comment by spencergibb** [comment]
Nothing we can do about it. It is a dependency of Eureka https://search.maven.org/artifact/com.netflix.eureka/eureka-core/1.9.8/jar

and there is an already issue in xstream.

**Comment by ochiama** [comment]
Hi, sorry to write on this closed ticket but please allow me to comment as I also don't want to raise a duplicate.

For a while, I've accepted the warning and monitored relevant issue tickets for resolution especially [XStream issue 101](https://github.com/x-stream/xstream/issues/101) which I feel is an underlying cause.

However, I have a concern because there seem to be no movement on that issue and a number of implementation is in violation of illegal reflective access. Now it is a warning with JDK 11, but once it is fully restricted, the use of XStream will not be possible.

Will there be a release for Eureka to address this, whether to use another library or change how XStream is used not to violate the illegal reflective access?

**Comment by spencergibb** [comment]
Nothing we can do about it. Either xstream needs to fix their issue or upstream eureka needs to move away from xstream.

**Comment by cordisvictor** [comment]
@spencergibb late, but maybe this is a good fit https://github.com/cordisvictor/easyml-lib

**Comment by spencergibb** [comment]
Great, propose it to Netflix
