### ISSUE TITLE
spring-cloud-starter-ribbon rxjava dependency is old

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-netflix#353]
RxJava dependency is 

```
<dependency>
            <groupId>com.netflix.rxjava</groupId>
            <artifactId>rxjava-core</artifactId>
        </dependency>
```
Should not this be:
```
 <dependency>
   <groupId>io.reactivex</groupId>
    <artifactId>rxjava</artifactId>
</dependency>
```
Because of this, its resulting in compile time error with ambiguous dependency, which makes one to manually exclude.

**Comment by brenuart** [comment]
Netflix artifacts declare dependencies to {{io.reacyivex:rxjava}} (the "old" one).
But {{org.sprigframework.cloud:spring-cloud-starter-ribbon}} explicitly add {{com.netflix.rxjava:rxjava-core}}

This pulls both dependencies together. Since they have overlapping content, it *may* produce weird issues... Hence the additional question _"why is {{org.sprigframework.cloud:spring-cloud-starter-ribbon}} using a different artificat than what Netflix uses?"_

**Comment by spencergibb** [comment]
newer version of ribbon is bringing in the new `io.reactivex:rxjava`, looking to see if there are any deps on the old
