### ISSUE TITLE
No qualifying bean of type 'org.springframework.core.env.Environment' available:

### ISSUE THREAD

**Issue by rk1023** [spring-cloud/spring-cloud-netflix#3810]
I am getting below error when I start SpringBoot(2.3.0 version) Application  :
**No qualifying bean of type 'org.springframework.core.env.Environment' available.**

This errors appears when I use @Autowired annotation with any component.

How to solve this issue ?

**Comment by spencergibb** [comment]
What does this have to do with spring cloud Netflix?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by izebit** [comment]
I am not sure, it's a solution to this problem or not. Anyway, I have faced the same problem.   
Spring boot application started failing after adding spring cloud config client dependency.  It turned out that my application involved bean called "environment" but its typed was not `org.springframework.core.env.Environment`. After changing the name of that bean, this problem disappred.
