### ISSUE TITLE
spring-cloud-netflix-hystrix module has been removed from spring-cloud-netflix

### ISSUE THREAD

**Issue by RakeshAMore** [spring-cloud/spring-cloud-netflix#4047]
**spring-cloud-netflix-hystrix module has been removed from spring-cloud-netflix**
I am working on upgrading my application on spring boot 2.5.x so subsequently I also need to move on the latest compatible version of spring cloud i.e. 2020.0.x (https://spring.io/projects/spring-cloud#overview). 
We have been using hystrix as Circuit breaker since long time and most of our apps are depends on this. But since netflix had stopped hystrix support in late 2018 and declared in maintenance mode, spring cloud netflix also removed spring-cloud-netflix-hystrix module.
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes-1
https://spring.io/blog/2019/12/23/spring-cloud-roadmap-and-hoxton-and-greenwich-maintenance-and-eol-announcements.

Now our challenge is we want to get upgraded on spring boot 2.5.x but we are blocked becuase of this deprecations.

**Solution Could be.**
Solution for this could be move to Resilience4j, but this is gone take some time(we have 200+ services). So we want to continue with hystrix.

**Or we can implement module similar to spring-cloud-netflix-hystrix.**
Another solution which we can think of implementing module similar to spring-cloud-netflix-hystrix. 

is any suggestion for how we can move ahead with hystrix?

**Comment by OlgaMaciaszek** [comment]
Hystrix core library is no longer supported by Netflix (https://github.com/Netflix/Hystrix/blob/master/README.md#hystrix-status), therefore we cannot provide support for its integration either, which we have announced a long time in advance before removing it (https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now). Since using non-maintained modules poses various issues, the most serious being lack of support for any security issues, we recommend you discontinue its use as soon as possible.

Our suggested replacement is [Spring Cloud CircuitBreaker](https://spring.io/projects/spring-cloud-circuitbreaker) + Resillience4J.

**Comment by RakeshAMore** [comment]
I am completely agree with you for discontinue hystrix, but we can not get rid off it right now due to some other dependent code. I appreciate your response to my question, will try to find some intermittent solution untill we migrate to Resillience4J. Thanks!
