### ISSUE TITLE
Getting all instance registry info without timeout

### ISSUE THREAD

**Issue by yangqiancheng90** [spring-cloud/spring-cloud-netflix#4110]
the version of eureka as follows:
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    <version>3.1.3</version>
</dependency>

I find that the method of RestTemplateTransportClientFactory#restTemplate(String serviceUrl) creates RestTemplate without config of timeout. This will cause getting all instance registry info timeout
 makes it much easier for us to diagnose the problem and to verify that

**Comment by kworkbee** [comment]
@OlgaMaciaszek I also recognized that a problem occurred in the heartbeat task when I configure Eureka high-availability due to no default timeout in `RestTemplate`.

When the servers were configured with peers, if increasing network latency was injected into a specific peer, the default timeout was not set in the `RestTemplate`, so it waited infinitely, and as a result, the `RetryableEurekaHttpClient` failed to add the host to the `quarantineSet` and the heartbeat task was repeated continuously.

There seems to be no progress in the previously registered PR, so I wrote a new one, so please review it positively. 😄
