### ISSUE TITLE
@EnableFeignClients - NullPointerException encoder in FeignClientFactoryBean

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-netflix#441]
I am using release train Angel.SR3. I am having the same issue as raised in gh-212. When `FeignClientFactoryBean` tries to build the Feign clients, `encoder` as well as all other autowired fields are null.

Basically I have:

* Main class annotated with `@SpringCloudApplication` and `@EnableFeignClients`
* An interface `UserClient` annotated with `@FeignClient`
* A class 'CompositeService` annotated @Service and autowiring `UserClient` (initializing this bean is where the failure occurs).

Looking at the DEBUG logs, the beans from `FeignAutoConfiguration` are not created until after the initialization of the above bean fails. I have tried putting `@EnableFeignClients` on the main class, a separate `@Configuration` class and a static inner class of another `@Configuration` class, all with the same result.

I have successfully used `@EnableFeignClients` in other sample projects I have made, so I am sure that the custom configuration I am providing is likely causing some timing issue. I am providing a number of custom auto-configuration classes that I am providing myself from an external library + 1 Bootstrap configuration.

I cannot produce a sample to reproduce because I am on a closed network and I am really having a hard time tracking down where the configuration problem may be in order to provide a reproducible sample. If someone could provide some ideas on what I should look for when debugging that would be really helpful. I can provide as much information as needed from logs and stack traces.

Thanks in advance.

**Comment by Koizumi85** [comment]
Hello,

are you using a milestone of spring-boot 1.3.0? If so you will have to go down to 1.2.5.RELEASE, because spring-cloud does not support spring-boot 1.3 at the moment. See https://github.com/spring-cloud/spring-cloud-netflix/issues/326 for morge informations.

Hope it helped

**Comment by steve-oakey** [comment]
No, I am using Spring Cloud Release Train Angel.SR3 which is using Spring Boot 1.2.4.

**Comment by brenuart** [comment]
`FeignClientFactoryBean` throws a `NullPointerException` because its autowired dependencies have not been set at the time the factory method is invoked.

After some investigations it appears the `GenericBeanDefinition` created by `FeignClientsRegistrar` doesn't say anything about its autowire mode leaving it to the default  `AbstractBeanDefinition.AUTOWIRE_NO` which doesn't make it eligible for autowiring.

A possible solution is to slightly change `FeignClientsRegistrar.createBeanDefinition()` and add the following to the created bean definition:

    definition.setAutowireMode(AbstractBeanDefinition.AUTOWIRE_BY_TYPE);

Note: should it by "BY_TYPE" or "BY_NAME" ?

**Comment by jmnarloch** [comment]
I am facing the same issue, the problem is that this is very hard to tackle down. I had compared the stack trace of working simple application and the one which is facing the problem.

Basically what I have found out is that for some reason the FeignClientFactoryBean depdencies are not getting resolved and FeignClientsConfiguration beans does not get registered in spring context. I tried different approaches to resolve this, by explicitly importing the FeignClientsConfiguration with highest possible precedence, but this didn't help. I had also noticed that whenever I remove 'org.springframework.security.oauth:spring-security-oauth2:2.0.7.RELEASE'
out of the project dependencies everything gets back to normal. I don't think that there is any issue with oauth itself, it's more likely that it causes to import some transitive dependency that pollutes the classpath.

If I will find anything I will let you know.

**Comment by steve-oakey** [comment]
Thanks for the replies. I have the problem when spring-security-oauth is not on the classpath, I am having trouble trying to figure out what dependency may be causing the issue.

**Comment by jmnarloch** [comment]
I have an exact log for comparision of working and failing setup. It turns out that fallback from Spring Security 4.0.1.RELASE to 3.2.8.RELEASE solved this problem in my case.

Please see: https://gist.github.com/jmnarloch/66f41c6904f97f84cef4
In the log title working you can see entries BeanPostProcessorChecker: feignDecoder ...

The same does not happen when you have Spring Security 4.0.1 on the classpath. I wonder why.
