### ISSUE TITLE
Service id based Zuul routing does not work with HTTPS

### ISSUE THREAD

**Issue by mkaberman** [spring-cloud/spring-cloud-netflix#459]
I tried to use https for my services using the service id:

        zuul: 
            routes:
              myservice: /appname/servicename/**

 and it does not seem to be working. When I specify the url and the port:

    zuul: 
        routes:
          myservice: 
            path: /appname/servicename/**
            url: https://localhost:9000/   

Zuul routs the request correctly. There are couple of problems with specifying service url:

1. I have to specify exact port for my services (I cannot use server.port=0 in my service's configuration). That prevents me from running two instances of a service on the same host.
2. I have to specify the host name. If I want to run my services on the host other than the one Zuul is running on I need to change Zuul's application.yml every time I deploy my service.
3. Even if I have two instances on my service running on different hosts it seems I still will not be able to load balance them. The Zuul documentation says: "These simple url-routes doesn’t get executed as HystrixCommand nor can you loadbalance multiple url with Ribbon."

Is https recommended to use with Zuul? It seems that that https use limits its functionality.

**Comment by dsyer** [comment]
Did you register your services in eureka? Did they set `eureka.instance.securePortEnabled=true`?

**Comment by mkaberman** [comment]
The services are registered in Eureka. I see them in Eureka's dashboard. My configuration is pretty simple.

My client:

        info:
          component: Discovery Service
        
        spring:
          application:
            name: discovery-service
            
        server:
          port: 9000
          ssl:
            enabled: true
            key-store: classpath:keystore.jks
            key-store-password: password
            key-alias: tomcat     

        eureka:
          instance:
            leaseRenewalIntervalInSeconds: 10
            securePortEnabled: true
          client:
            registryFetchIntervalSeconds: 5
            serviceUrl:
              defaultZone: https://localhost:8761/eureka/ 

Zuul:

        info:
          component: Zuul Server
          
        spring:
           application:
              name: distribmgt-proxy
              
        server:
          port: 8765
          ssl:
            enabled: true
            key-store: classpath:keystore.jks
            key-store-password: password
            key-alias: tomcat     
        
        zuul: 
            routes:
              discovery-service: /distribmgt/discovery/**
              
        eureka:
          instance:
            securePortEnabled: true
          client:
            serviceUrl:
              defaultZone: https://localhost:8761/eureka/ 
                
 Eureka:

     server:
        port: 8761
        ssl:
          enabled: true
          key-store: classpath:keystore.jks
          key-store-password: password
          key-alias: tomcat     
      
      eureka:
        instance:
         hostname: localhost
         securePortEnabled: true
        client:
          registerWithEureka: false
          fetchRegistry: false
        server:
          waitTimeInMsWhenSyncEmpty: 0


When I reference my component by id in Zuul config and try to execute the curl command:
   
            curl -k -i -X GET https://localhost:8765/distribmgt/discovery

I am getting the response:

     {"timestamp":1438089416153,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"Forwarding error"}

and Zuul throws the exception:

    com.netflix.zuul.exception.ZuulException: Forwarding error
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:146)
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:110)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
        at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
        at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120)
        at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:84)
        at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:111)
        at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:77)
        ....
    Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: discovery-serviceRibbonCommand failed and no fallback available.
        at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:816)
        at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:798)
    ....
    Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: discovery-service
        at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:468)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)

If I change my route to

     discovery-service:
        path: /distribmgt/discovery/**
        url: https://localhost:9000/

everything works.

**Comment by bka9** [comment]
So if you are using the serviceId to configure your routes the problem lies in the netflix library:

https://github.com/Netflix/ribbon/blob/master/ribbon-loadbalancer/src/main/java/com/netflix/loadbalancer/Server.java#L130-L164

It uses port 80 regardless of the protocol of the service. Not sure why. Would love to understand.

It appears that when you define the url like you have above, it uses a scheme registry to determine the default port of the scheme.

Looks like @spencergibb  made a commit a few days ago that fixes the problem:

https://github.com/spring-cloud/spring-cloud-netflix/commit/e5e677c0ada10a7023de87a4303f2afb162484fe

So until this is released you will have to specify the port in the service url.

**Comment by mkaberman** [comment]
I am building against the Spring Cloud snapshots, so I assumed that once a fix is checked in my build will pick it up. I just tried running my test again and the routing based on the component id is still not working with SSL enabled.

**Comment by shanman190** [comment]
I had this same problem and I found that the problem originates in how the DiscoveryClient on the client side finds instances. It uses two separate properties found on the EurekaInstanceConfigBean, 'vipAddress' and 'secureVipAddress', to choose instances. When you want to call a service using HTTPS you must configure the secureVipAddress to have the name of your service (I just reused `${spring.application.name}` in my application.yml just like the spring guys kindly do for the 'vipAddress') and that told eureka server that that service was HTTPS-enabled. Now the second part is to tell the client that that service is HTTPS-enabled. You can do this by using the following couple of properties: `ribbon.IsSecured=true` or `serviceId.ribbon.IsSecured=true`. With both of these components in place Ribbon will start sending the requests using HTTPS instead of HTTP.

**Comment by dsyer** [comment]
Setting `ribbon.IsSecured=true` seems like a hack to me. I think the Zuul routes should respect the service regstration that they came from.

**Comment by dsyer** [comment]
I'm not super proud of that implementation, but a vanilla `Server` instance doesn't have enough information on its own. Should be good enough for most purposes.

**Comment by rajaramkushwaha** [comment]
Hi,
My Application.propeties contains

zuul.routes.uberprodapi =/proxyapi/**
zuul.routes.serviceId =proxyapi   
proxyapi.ribbon.listOfServers= https://server/**

it is working fine for http, but for https  returning 301 

My ssl configuration is 
server.port = 8443
server.ssl.key-store = classpath:sample.jks
server.ssl.key-store-password = secret
server.ssl.key-password = password

Please suggest.

**Comment by rajaramkushwaha** [comment]
I had similar problem and it was configuration issue. 

Problem 1. it was manipulating target host as http , 
  for that error was typo, may be white space  ribbon.IsSecure: true 

Problem 2: target URL was getting build using port 80, for that solution is specify port in your list of server.

proxyprodapi: 
  ribbon:    
    listOfServers: https://api.proxy.com:443/**
otherwise calls gets redirected to port 80.

My use case was:  to build a centralized proxy for calling thirdparty api.

I have created sample app https://github.com/rajaramkushwaha/https-zuul-proxy-spring-boot-app/
its running fine. my application.yml is:

server: 
  port: 8443
  ssl:  
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password

ribbon: 
  TrustStore: keystore.jks
  TrustStorePassword : password
  ReadTimeout: 60000
  IsSecure: true
  MaxAutoRetries: 1
    

zuul:
  routes:
    uberprodapi: /proxyprodapi/**
    serviceId: proxyprodapi    
   
proxyprodapi: 
  ribbon:    
    listOfServers: https://api.proxy.com:443/**
    
        
# Disable Hystrix timeout globally (for all services)
hystrix: 
  command: 
    default:  
      execution:  
        timeout:  
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000

**Comment by dsyer** [comment]
Thanks for the update. AFAIK `ribbon.IsSecure: true` is enough if you set it to generate https URLs for all remotes (might require version 1.1 of Spring Cloud Netflix).

**Comment by praveenit219** [comment]
as per mkaberman question, we also face similar issue when we tried to connect to external https enabled server. when zuul is configured with 2way SSL. we are seeing connectivity issues with that external server, simplehostrequest class may have any issue ? it is ignoring SSL properties we set at JVM level or using system.properties at application level

**Comment by dsyer** [comment]
This is a very old issue and it is closed. If you still have an issue with the recent snapshots please post a sample project and open a new issue. Thanks.

**Comment by beku8** [comment]
+1, 
When setting direct url instead of by service id, https://{url}:443, solved this issue.
