### ISSUE TITLE
Zuul filter  and routing dynamic customizatiion

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-cloud/spring-cloud-netflix#618]
I wrote a zuul filter  and trying to override the route. Which is the api to override the routing and oveeride zuul  yaml file routing configuration. Example - 
- I took 2 apps store and customer
-  if in filter request body has specific value I want to send request fo differnt services.
- I got the values in filter and want to override pre-define route. I am trying to understand usage of ZUULROute API.

Please help.

**Comment by jmnarloch** [comment]
I'm not sure about your use case, but it looks like you don't definitely need dynamic routing yet. Since you have fixed number of services just configure the Zuul routes for them and afterwards add logic that will routes to the desired destination.

It simple to do with [UrlRewriter](http://tuckey.org/urlrewrite/), though you simply achieve the same by implementing simple Spring MVC controller.

**Comment by pradeepkusingh** [comment]
Thanks. My use case is simple- 

Based on area code I want to route the traffic to different services. Example if  area code starts with 303 this request should route to service version 1, if are code is 516 , request should route to service 2. This area code I am truncating from TN from request body.

**Comment by jmnarloch** [comment]
OK, so I had similar case though I had been doing matching based on the header value and for that purpose the UrlRewriter was enough, but I think that it won't be much helpful in your case since it looks like it doesn't have any rules to be specified for the request payload.

You have still two options:
* You can implement your own Zuul filter and register it in your application: https://github.com/Netflix/zuul/wiki/Writing-Filters and specify you logic there
* Alternatively you still can define Spring MVC controller or simple filter and just forward the request to the desired url through Zuul configures routes, but probably this isn't any better then custom Zuul filter.

**Comment by pradeepkusingh** [comment]
Thanks, I have created Zuul filter and extracted the value. Question is
which API I have to use in code to define routes ?

On Saturday, October 31, 2015, Jakub Narloch <notifications@github.com>
wrote:

> OK, so I had similar case though I had been doing matching based on the
> header value and for that purpose the UrlRewriter was enough, but I think
> that it won't be much helpful in your case since it looks like it doesn't
> have any rules to be specified for the request payload.
>
> You have still two options:
>
>    - You can implement your own Zuul filter and register it in your
>    application: https://github.com/Netflix/zuul/wiki/Writing-Filters and
>    specify you logic there
>    - Alternatively you still can define Spring MVC controller or simple
>    filter and just forward the request to the desired url through Zuul
>    configures routes, but probably this isn't any better then custom Zuul
>    filter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-netflix/issues/618#issuecomment-152748062>
> .
>


-- 
Thanks,
Pradeep Singh
Please excuse typos.

**Comment by spencergibb** [comment]
@pradeepkusingh will you be using static routes (to full urls) or dynamic routs (based on ribbon and eureka)?

**Comment by pradeepkusingh** [comment]
I will be using Ribbon and Eureka.

Thanks,
Pradeep Singh
Please excuse typos.

**Comment by pradeepkusingh** [comment]
spencergibb,  any update ?

**Comment by spencergibb** [comment]
@pradeepkusingh look at the `PreDecorationFilter` for an example of how to set the route.
