### ISSUE TITLE
Zuul proxy is not working with utf-8 urls

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-netflix#647]
I have a spring cloud app with Zuul proxy. My zuul proxy doesn't work with UTF-8 urls. How should I configure it?

This will work in my microservice, without proxy: ```http://localhost:8080/rest/item/гандан_тикет``` However when its behind a proxy ```http://localhost:9000/core/rest/item/гандан_тикет```
the гандан\_тикет will come as ```??????_?????``` into the microservice.

**Comment by beku8** [comment]
No update on this issue? If you could point a direction I will try to solve this issue & create a PR.

p.s Seems like a __Backlog__ to me, no?

**Comment by spencergibb** [comment]
@beku8 the Backlog tag was a dumb mistake on my part. I'm not sure where to start except for the zuul package.

**Comment by spencergibb** [comment]
This was the SO conversation that started this: http://stackoverflow.com/questions/33748934/zuul-proxy-is-not-working-with-utf-8-urls

**Comment by maxiplay** [comment]
+1

**Comment by NehemiahMi** [comment]
+1

**Comment by NehemiahMi** [comment]
@spencergibb     debug the module I know the bug is there:
[https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L101](url), where encodePath use encode is default "ISO-8859-1", but more url is other encode；so I think this is OK
----------------------------
String uriEncode = request.getCharacterEncoding();
				if (uriEncode == null){
					uriEncode = WebUtils.DEFAULT_CHARACTER_ENCODING;
				}
				uri = UriUtils.encodePath(contextURI, uriEncode);
---------------------------

**Comment by NehemiahMi** [comment]
sorry! code is this 。
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L101

**Comment by spencergibb** [comment]
Thanks @NehemiahMi!

**Comment by spencergibb** [comment]
I'm struggling to make a unit/integration test that fails with the existing code.
The following succeeds.

```
	@Test
	public void getUTF8Url() {
		String requestURI = "/\u00a5\u00a5";
		MockHttpServletRequest request = new MockHttpServletRequest("GET", requestURI);
		//request.setCharacterEncoding("UTF-8");
		MockHttpServletResponse response = new MockHttpServletResponse();

		RequestContext context = RequestContext.getCurrentContext();
		context.setRequest(request);
		context.setResponse(response);

		ProxyRequestHelper helper = new ProxyRequestHelper();

		String uri = helper.buildZuulRequestURI(request);

		assertThat(uri, is(requestURI));
	}
```

**Comment by spencergibb** [comment]
Nevermind, I was missing
```
		context.set("requestURI", requestURI);
```
so the uri was never getting encoded. I have a failing test now.

**Comment by spencergibb** [comment]
Hmm, what should the proper output be? 

With encoding 
```
Expected :/ascii/¥¥
Actual   :/ascii/%C2%A5%C2%A5
```
Without encoding 
```
Expected :/ascii/¥¥
Actual   :/ascii/%A5%A5
```

@NehemiahMi I'm guessing that's not what you expect.

**Comment by NehemiahMi** [comment]
I want to say：when I PCAP url ， this utf-8 url  '/ascii/¥¥' is '/ascii/%C2%A5%C2%A5' 。when I debug，in the zuul and spring-cloud-netflix, in this https://github.com/Netflix/zuul/blob/1.x/zuul-core/src/main/java/com/netflix/zuul/http/ZuulServlet.java#L81, which will route, meanwhile RequestContext will get 'requestURI' is '/ascii/¥¥' ,which Process  is   https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilter.java#L68   -> https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java#L223   ->   https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java#L322  (getContextPath  function)  ->   decodeRequestString  function ->  decodeInternal function  , pass the process the RequestContext will  put map 'requestURI' => '/ascii/¥¥'  in this code https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilter.java#L76。 so that will https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L98 contextURI is not null, but /ascii/¥¥, so .....,     I debug this process, please check it , in china now time  is too late, I am only remember it, maybe those place error a little,but the process is OK; please check it

**Comment by NehemiahMi** [comment]
@spencergibb   your test unit         RequestContext context = RequestContext.getCurrentContext();
context is null, 		String uri = request.getRequestURI();  uri get is right url coding,  but zuul in server-id route will replace uri to context.get('requestURI'), RequestContext must be right

**Comment by spencergibb** [comment]
@NehemiahMi sorry, I don't follow. The `RequestContext` is not null because of a `@Before`.

```
	@Before
	public void setTestRequestcontext() {
		RequestContext context = new RequestContext();
		RequestContext.testSetCurrentContext(context);
	}
```

**Comment by spencergibb** [comment]
ping @NehemiahMi or @beku8

**Comment by jebeaudet** [comment]
I just faced the same problem and the problem is that the path doesn't get properly reencoded before proxying to the backend. In `PreDecorationFilter`, in order to find the proper route, the path gets decoded using `UrlPathHelper`. This code path uses the `HttpServletRequest` encoding if set.

The same logic should be applied to the `ProxyRequestHelper` who reencode the path when building the backend request : 
```
    @Override
    public String buildZuulRequestURI(HttpServletRequest request)
    {
        RequestContext context = RequestContext.getCurrentContext();
        String uri = request.getRequestURI();
        String contextURI = (String) context.get("requestURI");
        if (contextURI != null) {
            try {
                uri = UriUtils.encodePath(contextURI,
                                          request.getCharacterEncoding() == null ? WebUtils.DEFAULT_CHARACTER_ENCODING
                                                                                : request.getCharacterEncoding());
            } catch (Exception e) {
                logger.debug("unable to encode uri path from context, falling back to uri from request", e);
            }
        }
        return uri;
    }
```

I've implemented this fix and it works properly. A request like this : 
`https://host/ol%C3%A9%D7%93%D7%A8%D7%A2%D7%A7`
should end up decoded like this in the end : 
`https://host/oléדרעק?`

The key here is that the proxy shouldn't change any of the parameters of the request!

**Comment by spencergibb** [comment]
@jebeaudet PR?

**Comment by jebeaudet** [comment]
I'll work on one, it's pretty trivial so it shouldn't take too long @spencergibb.
