### ISSUE TITLE
EnableTurbineAmqp is not available in Brixton.M4

### ISSUE THREAD

**Issue by sourabhhsharma** [spring-cloud/spring-cloud-netflix#752]
EnableTurbineAmqp gives following error in Brixton.M4

cannot find symbol
  symbol: class EnableTurbineAmqp
1 error

**Comment by herder** [comment]
Hi, 
`spring-cloud-starter-turbine-amqp` is deprecated in favor of `spring-cloud-starter-turbine-stream` You need to use `@EnableTurbineStream` and depend on one of the streaming implementations, like this: 

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-turbine-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>```

**Comment by sourabhhsharma** [comment]
Thanks Herder. It resolved the problem.
Could you please share any link that explains why turbine-amqp deprecated and turbine-stream preferred over it.

**Comment by herder** [comment]
Well, I don't have a link, but it seems reasonable to integrate this
functionality into the new streaming architecture which isn't tied to a
specific provider. :) That way, you can just as well use redis pub/sub
instead of rabbit, should you want to.

tors 21 jan. 2016 kl 16:13 skrev sourabhhsharma <notifications@github.com>:

**Comment by sourabhhsharma** [comment]
Thanks Herder for clarifying.
