### ISSUE TITLE
Provide a Zuul filter for rewriting Location header in responses

### ISSUE THREAD

**Issue by celkins** [spring-cloud/spring-cloud-netflix#8]
A common need, especially for hypermedia APIs, is to rewrite URLs in the response (both body and headers). I realize this is difficult to do for media types with no inherent knowledge of URLs (e.g., plain JSON), but it seems like something many people will end up writing themselves and poorly given the subtleties around `RequestContext.responseDataStream` and `RequestContext.responseBody`.

**Comment by zampettim** [comment]
I would suggest that either change the class to not be final, so it can be sub-classed, or provide an option to set the order. As it stands now, there is no way for someone to take this class and use it and still control the order if they need to, without forking the code.

**Comment by spencergibb** [comment]
@zampettim which class?

**Comment by zampettim** [comment]
I was looking at the Gist of ContentUrlRewritingFilter, which is marked as final. If there is something more recent I should look at instead, just let me know. The key point I'm trying to make is that as we start to see more pre-built filters, it needs to be kept in mind that the order of filters is really more of a runtime config decision, and less a compile-time decision. Having the ability to override or influence the order will eventually become important.

**Comment by dsyer** [comment]
Sorry I don't follow you. The code in the gist pasted above by @celkins is not part of this library. Or did I misunderstand?

**Comment by zampettim** [comment]
@dsyer You are correct, my comments are about the code in the Gist posted in @celkins. The subject of this issue is about a ZuulFilter that does content re-writing, and @celkins posted a Gist with a possible solution. My comment was directed to the possibility of taking his work and including it in the library. It appears that is not happening, or is not part of this ticket. That is fine. I didn't mean to confuse anyone. 

In general though, I would like to see any ZuulFilters that are included in the spring-cloud library be built in such a way that there is a way to override the ordering information, either through sub-classing or with a method to update the order. Should I open another issue to track this point instead?

**Comment by spencergibb** [comment]
@zampettim please open another issue for your zuul filter extensibility. I'm going to close this, as I don't think we want to maintain a general rewrite filter.

**Comment by dsyer** [comment]
This is re-opened so we can talk about a narrower scope: rewriting the "location" header only (no monkeying with response bodies).

**Comment by spencergibb** [comment]
That sounds like something we could handle.

**Comment by ryanjbaxter** [comment]
Closing this since #1863 addressed this issue
